# Generated by Django 3.0.7 on 2024-04-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios_presentacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
